version: "3.8"

services: 
 client:
  build: './app'
		ports: 
    - "3000:3000"
    networks: 
    - backend
    depends_on: 
    - server
    volumes: 
    - ./app:/home/node/app
    - /home/node/app/node_modules

server:
 build: './server'
  ports: 
  - "4000:4000"
  networks: 
  - backend
  depends_on: 
  - database
  volumes: 
  - ./server:/home/node/server
  - /home/node/server/node_modules
 database:
  image: "mongo"
 networks: 
  - backend
 ports: 
  - "27017:27017"
 networks:
  backend:


